#!/bin/sh

echo -n Try to bring eth0 interface up......>/dev/ttySAC0

if [ -f /etc/eth0-setting ] ; then
	source /etc/eth0-setting

    ifconfig eth0 down
    ifconfig eth0 hw ether $MAC
    ifconfig eth0 $IP netmask $Mask up
    route add default gw $Gateway
	echo nameserver $DNS > /etc/resolv.conf
else
	/sbin/ifconfig eth0 192.168.1.230 netmask 255.255.255.0 up
fi

echo Done > /dev/ttySAC0
