#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

/bin/hostname -F /etc/sysconfig/HOSTNAME

mount -a
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/hotplug

/sbin/ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0
